# PyGame settings
SCALING_FACTOR = 4
FRAMES = 60
WINDOW_SIZE = 850, 850

# Connection to RPi
HOST: str = "192.168.8.8"
PORT: int = 0
MUST_CONNECT = False

# Robot Attributes
ROBOT_LENGTH = 20 * SCALING_FACTOR
ROBOT_TURN_RADIUS = 30 * SCALING_FACTOR
ROBOT_SPEED_PER_SECOND = 20 * SCALING_FACTOR
ROBOT_S_FACTOR = ROBOT_LENGTH / ROBOT_TURN_RADIUS  # Please read briefing notes from Imperial

# Grid Attributes
GRID_LENGTH = 200 * SCALING_FACTOR
GRID_CELL_LENGTH = 10 * SCALING_FACTOR
GRID_START_BOX_LENGTH = 30 * SCALING_FACTOR

# Obstacle Attributes
OBSTACLE_SAFETY_WIDTH = 20 * SCALING_FACTOR
